export const COFFEE_BRANDS = 'COFFEE_BRANDS';
export const COFFEE_BRANDS_FACTORY = 'COFFEE_BRANDS_FACTORY';
export const COFFEE_BRANDS_INJECTABLE_FACTORY =
  'COFFEE_BRANDS_INJECTABLE_FACTORY';
export const COFFEE_BRANDS_INJECTABLE_ASYNC_FACTORY =
  'COFFEE_BRANDS_INJECTABLE_ASYNC_FACTORY';
